//! FHIR type metadata
//!
//! This module provides compile-time metadata about FHIR types, enabling
//! path resolution like "Patient.name.given" -> FhirPrimitiveType::String.
//!
//! Generated automatically - do not edit manually.

pub use phf;
use phf::{phf_map, Map};

mod resources;
pub use resources::*;
mod datatypes;
pub use datatypes::*;
mod primitives;
pub use primitives::*;
mod other;
pub use other::*;

/// FHIR primitive types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FhirPrimitiveType {
    Boolean,
    Integer,
    String,
    Date,
    DateTime,
    Instant,
    Time,
    Decimal,
    Uri,
    Url,
    Canonical,
    Code,
    Oid,
    Id,
    Markdown,
    Base64Binary,
    UnsignedInt,
    PositiveInt,
}

/// FHIR field type (primitive, complex, reference, or backbone element)
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FhirFieldType {
    Primitive(FhirPrimitiveType),
    Complex(&'static str),
    Reference,
    BackboneElement(&'static str),
}

/// Information about a field in a FHIR resource or datatype
#[derive(Debug, Clone)]
pub struct FieldInfo {
    pub field_type: FhirFieldType,
    pub min: u32,
    pub max: Option<u32>,
    pub is_choice_type: bool,
}

/// Main FHIR type registry mapping type names to their field metadata
pub static FHIR_TYPE_REGISTRY: Map<&'static str, &'static Map<&'static str, FieldInfo>> = phf_map! {
    "Account" => &ACCOUNT_FIELDS,
    "ActivityDefinition" => &ACTIVITYDEFINITION_FIELDS,
    "ActorDefinition" => &ACTORDEFINITION_FIELDS,
    "ActualGroup" => &ACTUALGROUP_FIELDS,
    "Address" => &ADDRESS_FIELDS,
    "AdministrableProductDefinition" => &ADMINISTRABLEPRODUCTDEFINITION_FIELDS,
    "AdverseEvent" => &ADVERSEEVENT_FIELDS,
    "Age" => &AGE_FIELDS,
    "AllergyIntolerance" => &ALLERGYINTOLERANCE_FIELDS,
    "Annotation" => &ANNOTATION_FIELDS,
    "Appointment" => &APPOINTMENT_FIELDS,
    "AppointmentResponse" => &APPOINTMENTRESPONSE_FIELDS,
    "ArtifactAssessment" => &ARTIFACTASSESSMENT_FIELDS,
    "Attachment" => &ATTACHMENT_FIELDS,
    "AuditEvent" => &AUDITEVENT_FIELDS,
    "Availability" => &AVAILABILITY_FIELDS,
    "BackboneElement" => &BACKBONEELEMENT_FIELDS,
    "BackboneType" => &BACKBONETYPE_FIELDS,
    "Base" => &BASE_FIELDS,
    "Basic" => &BASIC_FIELDS,
    "BatchBundle" => &BATCHBUNDLE_FIELDS,
    "BatchResponseBundle" => &BATCHRESPONSEBUNDLE_FIELDS,
    "Binary" => &BINARY_FIELDS,
    "BiologicallyDerivedProduct" => &BIOLOGICALLYDERIVEDPRODUCT_FIELDS,
    "BiologicallyDerivedProductDispense" => &BIOLOGICALLYDERIVEDPRODUCTDISPENSE_FIELDS,
    "BodyStructure" => &BODYSTRUCTURE_FIELDS,
    "Bundle" => &BUNDLE_FIELDS,
    "CDSHooksGuidanceResponse" => &CDSHOOKSGUIDANCERESPONSE_FIELDS,
    "CDSHooksRequestOrchestration" => &CDSHOOKSREQUESTORCHESTRATION_FIELDS,
    "CDSHooksServicePlanDefinition" => &CDSHOOKSSERVICEPLANDEFINITION_FIELDS,
    "CQLLibrary" => &CQLLIBRARY_FIELDS,
    "CanonicalResource" => &CANONICALRESOURCE_FIELDS,
    "CapabilityStatement" => &CAPABILITYSTATEMENT_FIELDS,
    "CarePlan" => &CAREPLAN_FIELDS,
    "CareTeam" => &CARETEAM_FIELDS,
    "ChargeItem" => &CHARGEITEM_FIELDS,
    "ChargeItemDefinition" => &CHARGEITEMDEFINITION_FIELDS,
    "Citation" => &CITATION_FIELDS,
    "Claim" => &CLAIM_FIELDS,
    "ClaimResponse" => &CLAIMRESPONSE_FIELDS,
    "ClinicalDocument" => &CLINICALDOCUMENT_FIELDS,
    "ClinicalImpression" => &CLINICALIMPRESSION_FIELDS,
    "ClinicalUseDefinition" => &CLINICALUSEDEFINITION_FIELDS,
    "CodeSystem" => &CODESYSTEM_FIELDS,
    "CodeableConcept" => &CODEABLECONCEPT_FIELDS,
    "CodeableReference" => &CODEABLEREFERENCE_FIELDS,
    "Coding" => &CODING_FIELDS,
    "Communication" => &COMMUNICATION_FIELDS,
    "CommunicationRequest" => &COMMUNICATIONREQUEST_FIELDS,
    "CompartmentDefinition" => &COMPARTMENTDEFINITION_FIELDS,
    "Composition" => &COMPOSITION_FIELDS,
    "ComputablePlanDefinition" => &COMPUTABLEPLANDEFINITION_FIELDS,
    "ComputableValueSet" => &COMPUTABLEVALUESET_FIELDS,
    "ConceptMap" => &CONCEPTMAP_FIELDS,
    "Condition" => &CONDITION_FIELDS,
    "ConditionDefinition" => &CONDITIONDEFINITION_FIELDS,
    "Consent" => &CONSENT_FIELDS,
    "ContactDetail" => &CONTACTDETAIL_FIELDS,
    "ContactPoint" => &CONTACTPOINT_FIELDS,
    "Contract" => &CONTRACT_FIELDS,
    "Contributor" => &CONTRIBUTOR_FIELDS,
    "Count" => &COUNT_FIELDS,
    "Coverage" => &COVERAGE_FIELDS,
    "CoverageEligibilityRequest" => &COVERAGEELIGIBILITYREQUEST_FIELDS,
    "CoverageEligibilityResponse" => &COVERAGEELIGIBILITYRESPONSE_FIELDS,
    "DataElement constraint on ElementDefinition data type" => &DATAELEMENT_CONSTRAINT_ON_ELEMENTDEFINITION_DATA_TYPE_FIELDS,
    "DataRequirement" => &DATAREQUIREMENT_FIELDS,
    "DataType" => &DATATYPE_FIELDS,
    "Definition" => &DEFINITION_FIELDS,
    "DetectedIssue" => &DETECTEDISSUE_FIELDS,
    "Device" => &DEVICE_FIELDS,
    "DeviceAssociation" => &DEVICEASSOCIATION_FIELDS,
    "DeviceDefinition" => &DEVICEDEFINITION_FIELDS,
    "DeviceDispense" => &DEVICEDISPENSE_FIELDS,
    "DeviceMetric" => &DEVICEMETRIC_FIELDS,
    "DeviceMetricObservationProfile" => &DEVICEMETRICOBSERVATIONPROFILE_FIELDS,
    "DeviceRequest" => &DEVICEREQUEST_FIELDS,
    "DeviceUsage" => &DEVICEUSAGE_FIELDS,
    "DiagnosticReport" => &DIAGNOSTICREPORT_FIELDS,
    "Distance" => &DISTANCE_FIELDS,
    "DocumentBundle" => &DOCUMENTBUNDLE_FIELDS,
    "DocumentReference" => &DOCUMENTREFERENCE_FIELDS,
    "DomainResource" => &DOMAINRESOURCE_FIELDS,
    "Dosage" => &DOSAGE_FIELDS,
    "Duration" => &DURATION_FIELDS,
    "EBMRecommendation" => &EBMRECOMMENDATION_FIELDS,
    "ELMLibrary" => &ELMLIBRARY_FIELDS,
    "Element" => &ELEMENT_FIELDS,
    "ElementDefinition" => &ELEMENTDEFINITION_FIELDS,
    "Encounter" => &ENCOUNTER_FIELDS,
    "EncounterHistory" => &ENCOUNTERHISTORY_FIELDS,
    "Endpoint" => &ENDPOINT_FIELDS,
    "EnrollmentRequest" => &ENROLLMENTREQUEST_FIELDS,
    "EnrollmentResponse" => &ENROLLMENTRESPONSE_FIELDS,
    "EpisodeOfCare" => &EPISODEOFCARE_FIELDS,
    "Event" => &EVENT_FIELDS,
    "EventDefinition" => &EVENTDEFINITION_FIELDS,
    "Evidence" => &EVIDENCE_FIELDS,
    "EvidenceReport" => &EVIDENCEREPORT_FIELDS,
    "EvidenceVariable" => &EVIDENCEVARIABLE_FIELDS,
    "ExampleLipidProfile" => &EXAMPLELIPIDPROFILE_FIELDS,
    "ExampleScenario" => &EXAMPLESCENARIO_FIELDS,
    "ExecutableValueSet" => &EXECUTABLEVALUESET_FIELDS,
    "ExplanationOfBenefit" => &EXPLANATIONOFBENEFIT_FIELDS,
    "Expression" => &EXPRESSION_FIELDS,
    "ExtendedContactDetail" => &EXTENDEDCONTACTDETAIL_FIELDS,
    "Extension" => &EXTENSION_FIELDS,
    "FHIRPathLibrary" => &FHIRPATHLIBRARY_FIELDS,
    "FamilyMemberHistory" => &FAMILYMEMBERHISTORY_FIELDS,
    "FamilyMemberHistoryForGeneticsAnalysis" => &FAMILYMEMBERHISTORYFORGENETICSANALYSIS_FIELDS,
    "FiveWs" => &FIVEWS_FIELDS,
    "Flag" => &FLAG_FIELDS,
    "FormularyItem" => &FORMULARYITEM_FIELDS,
    "GenomicStudy" => &GENOMICSTUDY_FIELDS,
    "Goal" => &GOAL_FIELDS,
    "GraphDefinition" => &GRAPHDEFINITION_FIELDS,
    "Group" => &GROUP_FIELDS,
    "GroupDefinition" => &GROUPDEFINITION_FIELDS,
    "GuidanceResponse" => &GUIDANCERESPONSE_FIELDS,
    "HealthcareService" => &HEALTHCARESERVICE_FIELDS,
    "HistoryBundle" => &HISTORYBUNDLE_FIELDS,
    "HumanName" => &HUMANNAME_FIELDS,
    "Identifier" => &IDENTIFIER_FIELDS,
    "ImagingSelection" => &IMAGINGSELECTION_FIELDS,
    "ImagingStudy" => &IMAGINGSTUDY_FIELDS,
    "Immunization" => &IMMUNIZATION_FIELDS,
    "ImmunizationEvaluation" => &IMMUNIZATIONEVALUATION_FIELDS,
    "ImmunizationRecommendation" => &IMMUNIZATIONRECOMMENDATION_FIELDS,
    "ImplementationGuide" => &IMPLEMENTATIONGUIDE_FIELDS,
    "Ingredient" => &INGREDIENT_FIELDS,
    "InsurancePlan" => &INSURANCEPLAN_FIELDS,
    "InventoryItem" => &INVENTORYITEM_FIELDS,
    "InventoryReport" => &INVENTORYREPORT_FIELDS,
    "Invoice" => &INVOICE_FIELDS,
    "Library" => &LIBRARY_FIELDS,
    "Linkage" => &LINKAGE_FIELDS,
    "List" => &LIST_FIELDS,
    "Location" => &LOCATION_FIELDS,
    "LogicLibrary" => &LOGICLIBRARY_FIELDS,
    "ManufacturedItemDefinition" => &MANUFACTUREDITEMDEFINITION_FIELDS,
    "MarketingStatus" => &MARKETINGSTATUS_FIELDS,
    "Measure" => &MEASURE_FIELDS,
    "MeasureReport" => &MEASUREREPORT_FIELDS,
    "Medication" => &MEDICATION_FIELDS,
    "MedicationAdministration" => &MEDICATIONADMINISTRATION_FIELDS,
    "MedicationDispense" => &MEDICATIONDISPENSE_FIELDS,
    "MedicationKnowledge" => &MEDICATIONKNOWLEDGE_FIELDS,
    "MedicationRequest" => &MEDICATIONREQUEST_FIELDS,
    "MedicationStatement" => &MEDICATIONSTATEMENT_FIELDS,
    "MedicinalProductDefinition" => &MEDICINALPRODUCTDEFINITION_FIELDS,
    "MessageDefinition" => &MESSAGEDEFINITION_FIELDS,
    "MessageHeader" => &MESSAGEHEADER_FIELDS,
    "Meta" => &META_FIELDS,
    "MetadataResource" => &METADATARESOURCE_FIELDS,
    "ModelInfoLibrary" => &MODELINFOLIBRARY_FIELDS,
    "ModuleDefinitionLibrary" => &MODULEDEFINITIONLIBRARY_FIELDS,
    "MolecularSequence" => &MOLECULARSEQUENCE_FIELDS,
    "MonetaryComponent" => &MONETARYCOMPONENT_FIELDS,
    "Money" => &MONEY_FIELDS,
    "MoneyQuantity" => &MONEYQUANTITY_FIELDS,
    "NamingSystem" => &NAMINGSYSTEM_FIELDS,
    "Narrative" => &NARRATIVE_FIELDS,
    "NutritionIntake" => &NUTRITIONINTAKE_FIELDS,
    "NutritionOrder" => &NUTRITIONORDER_FIELDS,
    "NutritionProduct" => &NUTRITIONPRODUCT_FIELDS,
    "Observation" => &OBSERVATION_FIELDS,
    "ObservationDefinition" => &OBSERVATIONDEFINITION_FIELDS,
    "Observationbmi" => &OBSERVATIONBMI_FIELDS,
    "Observationbodyheight" => &OBSERVATIONBODYHEIGHT_FIELDS,
    "Observationbodytemp" => &OBSERVATIONBODYTEMP_FIELDS,
    "Observationbodyweight" => &OBSERVATIONBODYWEIGHT_FIELDS,
    "Observationbp" => &OBSERVATIONBP_FIELDS,
    "Observationheadcircum" => &OBSERVATIONHEADCIRCUM_FIELDS,
    "Observationheartrate" => &OBSERVATIONHEARTRATE_FIELDS,
    "Observationoxygensat" => &OBSERVATIONOXYGENSAT_FIELDS,
    "Observationresprate" => &OBSERVATIONRESPRATE_FIELDS,
    "Observationvitalsigns" => &OBSERVATIONVITALSIGNS_FIELDS,
    "Observationvitalspanel" => &OBSERVATIONVITALSPANEL_FIELDS,
    "OperationDefinition" => &OPERATIONDEFINITION_FIELDS,
    "OperationOutcome" => &OPERATIONOUTCOME_FIELDS,
    "Organization" => &ORGANIZATION_FIELDS,
    "OrganizationAffiliation" => &ORGANIZATIONAFFILIATION_FIELDS,
    "PackagedProductDefinition" => &PACKAGEDPRODUCTDEFINITION_FIELDS,
    "ParameterDefinition" => &PARAMETERDEFINITION_FIELDS,
    "Parameters" => &PARAMETERS_FIELDS,
    "Participant" => &PARTICIPANT_FIELDS,
    "ParticipantContactable" => &PARTICIPANTCONTACTABLE_FIELDS,
    "ParticipantLiving" => &PARTICIPANTLIVING_FIELDS,
    "Patient" => &PATIENT_FIELDS,
    "PaymentNotice" => &PAYMENTNOTICE_FIELDS,
    "PaymentReconciliation" => &PAYMENTRECONCILIATION_FIELDS,
    "Period" => &PERIOD_FIELDS,
    "Permission" => &PERMISSION_FIELDS,
    "Person" => &PERSON_FIELDS,
    "PlanDefinition" => &PLANDEFINITION_FIELDS,
    "Practitioner" => &PRACTITIONER_FIELDS,
    "PractitionerRole" => &PRACTITIONERROLE_FIELDS,
    "PrimitiveType" => &PRIMITIVETYPE_FIELDS,
    "Procedure" => &PROCEDURE_FIELDS,
    "Product" => &PRODUCT_FIELDS,
    "ProductShelfLife" => &PRODUCTSHELFLIFE_FIELDS,
    "ProfileForCatalog" => &PROFILEFORCATALOG_FIELDS,
    "Provenance" => &PROVENANCE_FIELDS,
    "ProvenanceRelevantHistory" => &PROVENANCERELEVANTHISTORY_FIELDS,
    "Publishable" => &PUBLISHABLE_FIELDS,
    "PublishableActivityDefinition" => &PUBLISHABLEACTIVITYDEFINITION_FIELDS,
    "PublishableCodeSystem" => &PUBLISHABLECODESYSTEM_FIELDS,
    "PublishableConceptMap" => &PUBLISHABLECONCEPTMAP_FIELDS,
    "PublishableLibrary" => &PUBLISHABLELIBRARY_FIELDS,
    "PublishableMeasure" => &PUBLISHABLEMEASURE_FIELDS,
    "PublishableNamingSystem" => &PUBLISHABLENAMINGSYSTEM_FIELDS,
    "PublishablePlanDefinition" => &PUBLISHABLEPLANDEFINITION_FIELDS,
    "PublishableValueSet" => &PUBLISHABLEVALUESET_FIELDS,
    "Quantity" => &QUANTITY_FIELDS,
    "Questionnaire" => &QUESTIONNAIRE_FIELDS,
    "QuestionnaireResponse" => &QUESTIONNAIRERESPONSE_FIELDS,
    "Range" => &RANGE_FIELDS,
    "Ratio" => &RATIO_FIELDS,
    "RatioRange" => &RATIORANGE_FIELDS,
    "Reference" => &REFERENCE_FIELDS,
    "RegulatedAuthorization" => &REGULATEDAUTHORIZATION_FIELDS,
    "RelatedArtifact" => &RELATEDARTIFACT_FIELDS,
    "RelatedPerson" => &RELATEDPERSON_FIELDS,
    "Request" => &REQUEST_FIELDS,
    "RequestOrchestration" => &REQUESTORCHESTRATION_FIELDS,
    "Requirements" => &REQUIREMENTS_FIELDS,
    "ResearchStudy" => &RESEARCHSTUDY_FIELDS,
    "ResearchSubject" => &RESEARCHSUBJECT_FIELDS,
    "Resource" => &RESOURCE_FIELDS,
    "RiskAssessment" => &RISKASSESSMENT_FIELDS,
    "SampledData" => &SAMPLEDDATA_FIELDS,
    "Schedule" => &SCHEDULE_FIELDS,
    "SearchParameter" => &SEARCHPARAMETER_FIELDS,
    "SearchSetBundle" => &SEARCHSETBUNDLE_FIELDS,
    "ServiceRequest" => &SERVICEREQUEST_FIELDS,
    "Shareable" => &SHAREABLE_FIELDS,
    "ShareableActivityDefinition" => &SHAREABLEACTIVITYDEFINITION_FIELDS,
    "ShareableCodeSystem" => &SHAREABLECODESYSTEM_FIELDS,
    "ShareableConceptMap" => &SHAREABLECONCEPTMAP_FIELDS,
    "ShareableLibrary" => &SHAREABLELIBRARY_FIELDS,
    "ShareableMeasure" => &SHAREABLEMEASURE_FIELDS,
    "ShareableNamingSystem" => &SHAREABLENAMINGSYSTEM_FIELDS,
    "ShareablePlanDefinition" => &SHAREABLEPLANDEFINITION_FIELDS,
    "ShareableTestScript" => &SHAREABLETESTSCRIPT_FIELDS,
    "ShareableValueSet" => &SHAREABLEVALUESET_FIELDS,
    "Signature" => &SIGNATURE_FIELDS,
    "SimpleQuantity" => &SIMPLEQUANTITY_FIELDS,
    "Slot" => &SLOT_FIELDS,
    "Specimen" => &SPECIMEN_FIELDS,
    "SpecimenDefinition" => &SPECIMENDEFINITION_FIELDS,
    "StructureDefinition" => &STRUCTUREDEFINITION_FIELDS,
    "StructureMap" => &STRUCTUREMAP_FIELDS,
    "Subscription" => &SUBSCRIPTION_FIELDS,
    "SubscriptionNotificationBundle" => &SUBSCRIPTIONNOTIFICATIONBUNDLE_FIELDS,
    "SubscriptionStatus" => &SUBSCRIPTIONSTATUS_FIELDS,
    "SubscriptionTopic" => &SUBSCRIPTIONTOPIC_FIELDS,
    "Substance" => &SUBSTANCE_FIELDS,
    "SubstanceDefinition" => &SUBSTANCEDEFINITION_FIELDS,
    "SubstanceNucleicAcid" => &SUBSTANCENUCLEICACID_FIELDS,
    "SubstancePolymer" => &SUBSTANCEPOLYMER_FIELDS,
    "SubstanceProtein" => &SUBSTANCEPROTEIN_FIELDS,
    "SubstanceReferenceInformation" => &SUBSTANCEREFERENCEINFORMATION_FIELDS,
    "SubstanceSourceMaterial" => &SUBSTANCESOURCEMATERIAL_FIELDS,
    "SupplyDelivery" => &SUPPLYDELIVERY_FIELDS,
    "SupplyRequest" => &SUPPLYREQUEST_FIELDS,
    "Task" => &TASK_FIELDS,
    "TerminologyCapabilities" => &TERMINOLOGYCAPABILITIES_FIELDS,
    "TestPlan" => &TESTPLAN_FIELDS,
    "TestReport" => &TESTREPORT_FIELDS,
    "TestScript" => &TESTSCRIPT_FIELDS,
    "Timing" => &TIMING_FIELDS,
    "TransactionBundle" => &TRANSACTIONBUNDLE_FIELDS,
    "TransactionResponseBundle" => &TRANSACTIONRESPONSEBUNDLE_FIELDS,
    "Transport" => &TRANSPORT_FIELDS,
    "TriggerDefinition" => &TRIGGERDEFINITION_FIELDS,
    "UsageContext" => &USAGECONTEXT_FIELDS,
    "ValueSet" => &VALUESET_FIELDS,
    "VerificationResult" => &VERIFICATIONRESULT_FIELDS,
    "VirtualServiceDetail" => &VIRTUALSERVICEDETAIL_FIELDS,
    "VisionPrescription" => &VISIONPRESCRIPTION_FIELDS,
    "base64Binary" => &BASE64BINARY_FIELDS,
    "boolean" => &BOOLEAN_FIELDS,
    "canonical" => &CANONICAL_FIELDS,
    "code" => &CODE_FIELDS,
    "date" => &DATE_FIELDS,
    "dateTime" => &DATETIME_FIELDS,
    "decimal" => &DECIMAL_FIELDS,
    "id" => &ID_FIELDS,
    "instant" => &INSTANT_FIELDS,
    "integer" => &INTEGER_FIELDS,
    "integer64" => &INTEGER64_FIELDS,
    "markdown" => &MARKDOWN_FIELDS,
    "oid" => &OID_FIELDS,
    "positiveInt" => &POSITIVEINT_FIELDS,
    "string" => &STRING_FIELDS,
    "time" => &TIME_FIELDS,
    "unsignedInt" => &UNSIGNEDINT_FIELDS,
    "uri" => &URI_FIELDS,
    "url" => &URL_FIELDS,
    "uuid" => &UUID_FIELDS,
    "xhtml" => &XHTML_FIELDS,
};

/// Get field information for a specific field in a type
pub fn get_field_info(type_name: &str, field_name: &str) -> Option<&'static FieldInfo> {
    FHIR_TYPE_REGISTRY
        .get(type_name)
        .and_then(|fields| fields.get(field_name))
}

/// Resolve a nested path like "Patient.name.given" to its field type
pub fn resolve_path(path: &str) -> Option<&'static FhirFieldType> {
    let parts: Vec<&str> = path.split('.').collect();
    if parts.is_empty() {
        return None;
    }

    let mut current_type_name = parts[0];

    for (idx, &field_name) in parts[1..].iter().enumerate() {
        let field_info = get_field_info(current_type_name, field_name)?;

        // If this is the last field, return its type
        if idx == parts.len() - 2 {
            return Some(&field_info.field_type);
        }

        // Otherwise, navigate to the next type
        match &field_info.field_type {
            FhirFieldType::Complex(type_name) | FhirFieldType::BackboneElement(type_name) => {
                current_type_name = type_name;
            }
            _ => return None, // Can't navigate further
        }
    }

    None
}
