# rust-analyzer configuration
# This file is tracked in git and applies to the workspace

[cargo]
# Enable all features when analyzing
features = "all"

[procMacro]
# Enable procedural macro expansion
enable = true
# Ignore wasm-bindgen proc macro errors when not targeting wasm
ignored = { "wasm-bindgen" = ["getter", "readonly"] }

[procMacro.attributes]
# Enable attribute macro expansion
enable = true

[diagnostics]
# Disable proc-macro diagnostics for wasm-bindgen
disabled = ["macro-error"]
