//! FHIR type metadata
//!
//! This module provides compile-time metadata about FHIR types, enabling
//! path resolution like "Patient.name.given" -> FhirPrimitiveType::String.
//!
//! Generated automatically - do not edit manually.

pub use phf;
use phf::{phf_map, Map};

mod resources;
pub use resources::*;
mod datatypes;
pub use datatypes::*;
mod primitives;
pub use primitives::*;
mod other;
pub use other::*;

/// FHIR primitive types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FhirPrimitiveType {
    Boolean,
    Integer,
    String,
    Date,
    DateTime,
    Instant,
    Time,
    Decimal,
    Uri,
    Url,
    Canonical,
    Code,
    Oid,
    Id,
    Markdown,
    Base64Binary,
    UnsignedInt,
    PositiveInt,
}

/// FHIR field type (primitive, complex, reference, or backbone element)
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FhirFieldType {
    Primitive(FhirPrimitiveType),
    Complex(&'static str),
    Reference,
    BackboneElement(&'static str),
}

/// Information about a field in a FHIR resource or datatype
#[derive(Debug, Clone)]
pub struct FieldInfo {
    pub field_type: FhirFieldType,
    pub min: u32,
    pub max: Option<u32>,
    pub is_choice_type: bool,
}

/// Main FHIR type registry mapping type names to their field metadata
pub static FHIR_TYPE_REGISTRY: Map<&'static str, &'static Map<&'static str, FieldInfo>> = phf_map! {
    "Provenance" => &PROVENANCE_FIELDS,
    "instant" => &INSTANT_FIELDS,
    "bestpractice-explanation" => &BESTPRACTICE_EXPLANATION_FIELDS,
    "match-grade" => &MATCH_GRADE_FIELDS,
    "ADXP-careOf" => &ADXP_CAREOF_FIELDS,
    "profile-element" => &PROFILE_ELEMENT_FIELDS,
    "Substance" => &SUBSTANCE_FIELDS,
    "recipientType" => &RECIPIENTTYPE_FIELDS,
    "GraphDefinition" => &GRAPHDEFINITION_FIELDS,
    "Library" => &LIBRARY_FIELDS,
    "initialValue" => &INITIALVALUE_FIELDS,
    "DiagnosticReport" => &DIAGNOSTICREPORT_FIELDS,
    "DetectedIssue" => &DETECTEDISSUE_FIELDS,
    "partner-prefix" => &PARTNER_PREFIX_FIELDS,
    "EN-use" => &EN_USE_FIELDS,
    "canonical" => &CANONICAL_FIELDS,
    "instantiatesUri" => &INSTANTIATESURI_FIELDS,
    "otherName" => &OTHERNAME_FIELDS,
    "Composition" => &COMPOSITION_FIELDS,
    "HealthcareService" => &HEALTHCARESERVICE_FIELDS,
    "dateTime" => &DATETIME_FIELDS,
    "question" => &QUESTION_FIELDS,
    "Duration" => &DURATION_FIELDS,
    "rules-text" => &RULES_TEXT_FIELDS,
    "dayOfMonth" => &DAYOFMONTH_FIELDS,
    "expirationDate" => &EXPIRATIONDATE_FIELDS,
    "applicable-version" => &APPLICABLE_VERSION_FIELDS,
    "specialHandling" => &SPECIALHANDLING_FIELDS,
    "AdverseEvent" => &ADVERSEEVENT_FIELDS,
    "activityStatusDate" => &ACTIVITYSTATUSDATE_FIELDS,
    "ContactDetail" => &CONTACTDETAIL_FIELDS,
    "OrganizationAffiliation" => &ORGANIZATIONAFFILIATION_FIELDS,
    "RelatedPerson" => &RELATEDPERSON_FIELDS,
    "outcome" => &OUTCOME_FIELDS,
    "addendumOf" => &ADDENDUMOF_FIELDS,
    "preferredContact" => &PREFERREDCONTACT_FIELDS,
    "MedicationKnowledge" => &MEDICATIONKNOWLEDGE_FIELDS,
    "OperationOutcome" => &OPERATIONOUTCOME_FIELDS,
    "styleSensitive" => &STYLESENSITIVE_FIELDS,
    "reasonCancelled" => &REASONCANCELLED_FIELDS,
    "Item" => &ITEM_FIELDS,
    "MedicinalProductIndication" => &MEDICINALPRODUCTINDICATION_FIELDS,
    "Population" => &POPULATION_FIELDS,
    "primaryInd" => &PRIMARYIND_FIELDS,
    "DiagnosticReport-Genetics" => &DIAGNOSTICREPORT_GENETICS_FIELDS,
    "delta" => &DELTA_FIELDS,
    "Clinical Document" => &CLINICAL_DOCUMENT_FIELDS,
    "UsageContext" => &USAGECONTEXT_FIELDS,
    "Group Definition" => &GROUP_DEFINITION_FIELDS,
    "trusted-expansion" => &TRUSTED_EXPANSION_FIELDS,
    "basedOn" => &BASEDON_FIELDS,
    "ADXP-delimiter" => &ADXP_DELIMITER_FIELDS,
    "PhaseSet" => &PHASESET_FIELDS,
    "Measure" => &MEASURE_FIELDS,
    "style" => &STYLE_FIELDS,
    "recipientLanguage" => &RECIPIENTLANGUAGE_FIELDS,
    "referenceResource" => &REFERENCERESOURCE_FIELDS,
    "DeviceMetric" => &DEVICEMETRIC_FIELDS,
    "objectClass" => &OBJECTCLASS_FIELDS,
    "targetBodyStructure" => &TARGETBODYSTRUCTURE_FIELDS,
    "baseType" => &BASETYPE_FIELDS,
    "Quantity" => &QUANTITY_FIELDS,
    "CapabilityStatement" => &CAPABILITYSTATEMENT_FIELDS,
    "parent" => &PARENT_FIELDS,
    "cdsHooksEndpoint" => &CDSHOOKSENDPOINT_FIELDS,
    "standards-status" => &STANDARDS_STATUS_FIELDS,
    "precondition" => &PRECONDITION_FIELDS,
    "Basic" => &BASIC_FIELDS,
    "performerFunction" => &PERFORMERFUNCTION_FIELDS,
    "SC-coding" => &SC_CODING_FIELDS,
    "Group" => &GROUP_FIELDS,
    "mothers-family" => &MOTHERS_FAMILY_FIELDS,
    "extension" => &EXTENSION_FIELDS,
    "validDate" => &VALIDDATE_FIELDS,
    "MoneyQuantity" => &MONEYQUANTITY_FIELDS,
    "ResearchSubject" => &RESEARCHSUBJECT_FIELDS,
    "certainty" => &CERTAINTY_FIELDS,
    "DocumentReference" => &DOCUMENTREFERENCE_FIELDS,
    "FiveWs" => &FIVEWS_FIELDS,
    "completionMode" => &COMPLETIONMODE_FIELDS,
    "genderIdentity" => &GENDERIDENTITY_FIELDS,
    "doNotPerform" => &DONOTPERFORM_FIELDS,
    "specimenCode" => &SPECIMENCODE_FIELDS,
    "integer" => &INTEGER_FIELDS,
    "animalSpecies" => &ANIMALSPECIES_FIELDS,
    "StructureMap" => &STRUCTUREMAP_FIELDS,
    "profile" => &PROFILE_FIELDS,
    "Medication" => &MEDICATION_FIELDS,
    "Address" => &ADDRESS_FIELDS,
    "management" => &MANAGEMENT_FIELDS,
    "warning" => &WARNING_FIELDS,
    "deviceCode" => &DEVICECODE_FIELDS,
    "CarePlan" => &CAREPLAN_FIELDS,
    "related" => &RELATED_FIELDS,
    "RiskEvidenceSynthesis" => &RISKEVIDENCESYNTHESIS_FIELDS,
    "ADXP-deliveryInstallationType" => &ADXP_DELIVERYINSTALLATIONTYPE_FIELDS,
    "Binary" => &BINARY_FIELDS,
    "search-parameter-combination" => &SEARCH_PARAMETER_COMBINATION_FIELDS,
    "bindingName" => &BINDINGNAME_FIELDS,
    "ParameterDefinition" => &PARAMETERDEFINITION_FIELDS,
    "group" => &GROUP_FIELDS,
    "reagent" => &REAGENT_FIELDS,
    "patientInstruction" => &PATIENTINSTRUCTION_FIELDS,
    "calculatedValue" => &CALCULATEDVALUE_FIELDS,
    "Family member history for genetics analysis" => &FAMILY_MEMBER_HISTORY_FOR_GENETICS_ANALYSIS_FIELDS,
    "Parameters" => &PARAMETERS_FIELDS,
    "haploid" => &HAPLOID_FIELDS,
    "EffectEvidenceSynthesis" => &EFFECTEVIDENCESYNTHESIS_FIELDS,
    "schedule" => &SCHEDULE_FIELDS,
    "VisionPrescription" => &VISIONPRESCRIPTION_FIELDS,
    "ImplementationGuide" => &IMPLEMENTATIONGUIDE_FIELDS,
    "CQL Library" => &CQL_LIBRARY_FIELDS,
    "TriggerDefinition" => &TRIGGERDEFINITION_FIELDS,
    "DNARegionName" => &DNAREGIONNAME_FIELDS,
    "allele-database" => &ALLELE_DATABASE_FIELDS,
    "NamingSystem" => &NAMINGSYSTEM_FIELDS,
    "ADXP-censusTract" => &ADXP_CENSUSTRACT_FIELDS,
    "birthPlace" => &BIRTHPLACE_FIELDS,
    "priority" => &PRIORITY_FIELDS,
    "Shareable CodeSystem" => &SHAREABLE_CODESYSTEM_FIELDS,
    "time" => &TIME_FIELDS,
    "episodeOfCare" => &EPISODEOFCARE_FIELDS,
    "Appointment" => &APPOINTMENT_FIELDS,
    "expression" => &EXPRESSION_FIELDS,
    "Display Name" => &DISPLAY_NAME_FIELDS,
    "observation" => &OBSERVATION_FIELDS,
    "resolutionAge" => &RESOLUTIONAGE_FIELDS,
    "MedicinalProductPharmaceutical" => &MEDICINALPRODUCTPHARMACEUTICAL_FIELDS,
    "type" => &TYPE_FIELDS,
    "Original Text" => &ORIGINAL_TEXT_FIELDS,
    "preferenceType" => &PREFERENCETYPE_FIELDS,
    "fathers-family" => &FATHERS_FAMILY_FIELDS,
    "extensible" => &EXTENSIBLE_FIELDS,
    "authoritativeSource" => &AUTHORITATIVESOURCE_FIELDS,
    "Communication" => &COMMUNICATION_FIELDS,
    "Anonymized" => &ANONYMIZED_FIELDS,
    "permitted-value-conceptmap" => &PERMITTED_VALUE_CONCEPTMAP_FIELDS,
    "referenceProfile" => &REFERENCEPROFILE_FIELDS,
    "otherConfidentiality" => &OTHERCONFIDENTIALITY_FIELDS,
    "reasonRejected" => &REASONREJECTED_FIELDS,
    "Slot" => &SLOT_FIELDS,
    "json-type" => &JSON_TYPE_FIELDS,
    "nullFlavor" => &NULLFLAVOR_FIELDS,
    "SubstanceAmount" => &SUBSTANCEAMOUNT_FIELDS,
    "performerOrder" => &PERFORMERORDER_FIELDS,
    "xml-no-order" => &XML_NO_ORDER_FIELDS,
    "daysOfCycle" => &DAYSOFCYCLE_FIELDS,
    "ContactPoint" => &CONTACTPOINT_FIELDS,
    "ADXP-postBox" => &ADXP_POSTBOX_FIELDS,
    "EnrollmentResponse" => &ENROLLMENTRESPONSE_FIELDS,
    "url" => &URL_FIELDS,
    "dependencies" => &DEPENDENCIES_FIELDS,
    "SubstanceReferenceInformation" => &SUBSTANCEREFERENCEINFORMATION_FIELDS,
    "incisionDateTime" => &INCISIONDATETIME_FIELDS,
    "Immunization" => &IMMUNIZATION_FIELDS,
    "adoptionInfo" => &ADOPTIONINFO_FIELDS,
    "mimeType" => &MIMETYPE_FIELDS,
    "ValidityPeriod" => &VALIDITYPERIOD_FIELDS,
    "MedicinalProductPackaged" => &MEDICINALPRODUCTPACKAGED_FIELDS,
    "ProdCharacteristic" => &PRODCHARACTERISTIC_FIELDS,
    "Actual Group" => &ACTUAL_GROUP_FIELDS,
    "Patient" => &PATIENT_FIELDS,
    "concept-comments" => &CONCEPT_COMMENTS_FIELDS,
    "exposureDuration" => &EXPOSUREDURATION_FIELDS,
    "abatement" => &ABATEMENT_FIELDS,
    "ElementDefinition" => &ELEMENTDEFINITION_FIELDS,
    "encounterClass" => &ENCOUNTERCLASS_FIELDS,
    "Transcriber" => &TRANSCRIBER_FIELDS,
    "ProductShelfLife" => &PRODUCTSHELFLIFE_FIELDS,
    "workflowStatus" => &WORKFLOWSTATUS_FIELDS,
    "EN-qualifier" => &EN_QUALIFIER_FIELDS,
    "minOccurs" => &MINOCCURS_FIELDS,
    "disability" => &DISABILITY_FIELDS,
    "http-response-header" => &HTTP_RESPONSE_HEADER_FIELDS,
    "ActivityDefinition" => &ACTIVITYDEFINITION_FIELDS,
    "fhirType" => &FHIRTYPE_FIELDS,
    "AppointmentResponse" => &APPOINTMENTRESPONSE_FIELDS,
    "duration" => &DURATION_FIELDS,
    "issue-source" => &ISSUE_SOURCE_FIELDS,
    "Observation-genetics" => &OBSERVATION_GENETICS_FIELDS,
    "TestReport" => &TESTREPORT_FIELDS,
    "MeasureReport" => &MEASUREREPORT_FIELDS,
    "TerminologyCapabilities" => &TERMINOLOGYCAPABILITIES_FIELDS,
    "Procedure" => &PROCEDURE_FIELDS,
    "MPPS" => &MPPS_FIELDS,
    "date" => &DATE_FIELDS,
    "CQF-Questionnaire" => &CQF_QUESTIONNAIRE_FIELDS,
    "CatalogEntry" => &CATALOGENTRY_FIELDS,
    "signatureRequired" => &SIGNATUREREQUIRED_FIELDS,
    "Interpretation" => &INTERPRETATION_FIELDS,
    "isCommonBinding" => &ISCOMMONBINDING_FIELDS,
    "own-prefix" => &OWN_PREFIX_FIELDS,
    "media" => &MEDIA_FIELDS,
    "religion" => &RELIGION_FIELDS,
    "unitOption" => &UNITOPTION_FIELDS,
    "Profile for Catalog" => &PROFILE_FOR_CATALOG_FIELDS,
    "Distance" => &DISTANCE_FIELDS,
    "initiatingPerson" => &INITIATINGPERSON_FIELDS,
    "fmm" => &FMM_FIELDS,
    "InsurancePlan" => &INSURANCEPLAN_FIELDS,
    "systemUserTaskContext" => &SYSTEMUSERTASKCONTEXT_FIELDS,
    "ConceptMap" => &CONCEPTMAP_FIELDS,
    "observation-headcircum" => &OBSERVATION_HEADCIRCUM_FIELDS,
    "concept-definition" => &CONCEPT_DEFINITION_FIELDS,
    "MedicationAdministration" => &MEDICATIONADMINISTRATION_FIELDS,
    "section-subject" => &SECTION_SUBJECT_FIELDS,
    "Meta" => &META_FIELDS,
    "maxSize" => &MAXSIZE_FIELDS,
    "minValueSet" => &MINVALUESET_FIELDS,
    "identifier" => &IDENTIFIER_FIELDS,
    "ADXP-unitType" => &ADXP_UNITTYPE_FIELDS,
    "receivingOrganization" => &RECEIVINGORGANIZATION_FIELDS,
    "HumanName" => &HUMANNAME_FIELDS,
    "category" => &CATEGORY_FIELDS,
    "versionNumber" => &VERSIONNUMBER_FIELDS,
    "DeviceDefinition" => &DEVICEDEFINITION_FIELDS,
    "NumberOfInstances" => &NUMBEROFINSTANCES_FIELDS,
    "maxDecimalPlaces" => &MAXDECIMALPLACES_FIELDS,
    "replacedby" => &REPLACEDBY_FIELDS,
    "Organization" => &ORGANIZATION_FIELDS,
    "congregation" => &CONGREGATION_FIELDS,
    "pertainsToGoal" => &PERTAINSTOGOAL_FIELDS,
    "Relative Date Criteria" => &RELATIVE_DATE_CRITERIA_FIELDS,
    "careplan" => &CAREPLAN_FIELDS,
    "EnrollmentRequest" => &ENROLLMENTREQUEST_FIELDS,
    "BiologicallyDerivedProduct" => &BIOLOGICALLYDERIVEDPRODUCT_FIELDS,
    "reasonReference" => &REASONREFERENCE_FIELDS,
    "Contributor" => &CONTRIBUTOR_FIELDS,
    "optionExclusive" => &OPTIONEXCLUSIVE_FIELDS,
    "allowed-type" => &ALLOWED_TYPE_FIELDS,
    "code" => &CODE_FIELDS,
    "Consent" => &CONSENT_FIELDS,
    "Task" => &TASK_FIELDS,
    "Shareable ActivityDefinition" => &SHAREABLE_ACTIVITYDEFINITION_FIELDS,
    "Accession" => &ACCESSION_FIELDS,
    "activity-title" => &ACTIVITY_TITLE_FIELDS,
    "Data Absent Reason" => &DATA_ABSENT_REASON_FIELDS,
    "MedicinalProductContraindication" => &MEDICINALPRODUCTCONTRAINDICATION_FIELDS,
    "sctdescid" => &SCTDESCID_FIELDS,
    "Timezone Code" => &TIMEZONE_CODE_FIELDS,
    "SupplyDelivery" => &SUPPLYDELIVERY_FIELDS,
    "QuestionnaireResponse" => &QUESTIONNAIRERESPONSE_FIELDS,
    "effectiveDate" => &EFFECTIVEDATE_FIELDS,
    "acceptance" => &ACCEPTANCE_FIELDS,
    "reasonRefuted" => &REASONREFUTED_FIELDS,
    "prohibited" => &PROHIBITED_FIELDS,
    "base64Binary" => &BASE64BINARY_FIELDS,
    "SubstanceSpecification" => &SUBSTANCESPECIFICATION_FIELDS,
    "optionPrefix" => &OPTIONPREFIX_FIELDS,
    "FamilyMemberHistory" => &FAMILYMEMBERHISTORY_FIELDS,
    "country" => &COUNTRY_FIELDS,
    "relatedPerson" => &RELATEDPERSON_FIELDS,
    "xml-type" => &XML_TYPE_FIELDS,
    "qualityOfEvidence" => &QUALITYOFEVIDENCE_FIELDS,
    "local" => &LOCAL_FIELDS,
    "interpreterRequired" => &INTERPRETERREQUIRED_FIELDS,
    "allowedUnits" => &ALLOWEDUNITS_FIELDS,
    "Computable PlanDefinition" => &COMPUTABLE_PLANDEFINITION_FIELDS,
    "administration" => &ADMINISTRATION_FIELDS,
    "referenceFilter" => &REFERENCEFILTER_FIELDS,
    "oid" => &OID_FIELDS,
    "ADXP-precinct" => &ADXP_PRECINCT_FIELDS,
    "GenomicSourceClass" => &GENOMICSOURCECLASS_FIELDS,
    "display-hint" => &DISPLAY_HINT_FIELDS,
    "severity" => &SEVERITY_FIELDS,
    "Device Metric Observation Profile" => &DEVICE_METRIC_OBSERVATION_PROFILE_FIELDS,
    "Resource" => &RESOURCE_FIELDS,
    "MedicinalProductManufactured" => &MEDICINALPRODUCTMANUFACTURED_FIELDS,
    "wg" => &WG_FIELDS,
    "table-name" => &TABLE_NAME_FIELDS,
    "PaymentNotice" => &PAYMENTNOTICE_FIELDS,
    "expand-rules" => &EXPAND_RULES_FIELDS,
    "messageheader-response-request" => &MESSAGEHEADER_RESPONSE_REQUEST_FIELDS,
    "CoverageEligibilityResponse" => &COVERAGEELIGIBILITYRESPONSE_FIELDS,
    "unclosed" => &UNCLOSED_FIELDS,
    "EventDefinition" => &EVENTDEFINITION_FIELDS,
    "CommunicationRequest" => &COMMUNICATIONREQUEST_FIELDS,
    "BodyStructure Reference" => &BODYSTRUCTURE_REFERENCE_FIELDS,
    "ADXP-buildingNumberSuffix" => &ADXP_BUILDINGNUMBERSUFFIX_FIELDS,
    "ExampleScenario" => &EXAMPLESCENARIO_FIELDS,
    "AssessedCondition" => &ASSESSEDCONDITION_FIELDS,
    "capabilities" => &CAPABILITIES_FIELDS,
    "CodeableConcept" => &CODEABLECONCEPT_FIELDS,
    "maxValueSet" => &MAXVALUESET_FIELDS,
    "map" => &MAP_FIELDS,
    "constraint" => &CONSTRAINT_FIELDS,
    "Practitioner" => &PRACTITIONER_FIELDS,
    "ClaimResponse" => &CLAIMRESPONSE_FIELDS,
    "ADXP-streetNameBase" => &ADXP_STREETNAMEBASE_FIELDS,
    "Coverage" => &COVERAGE_FIELDS,
    "patient-record" => &PATIENT_RECORD_FIELDS,
    "uri" => &URI_FIELDS,
    "deprecated" => &DEPRECATED_FIELDS,
    "reviewer" => &REVIEWER_FIELDS,
    "ImmunizationRecommendation" => &IMMUNIZATIONRECOMMENDATION_FIELDS,
    "Profile for HLA Genotyping Results" => &PROFILE_FOR_HLA_GENOTYPING_RESULTS_FIELDS,
    "minValue" => &MINVALUE_FIELDS,
    "modeOfArrival" => &MODEOFARRIVAL_FIELDS,
    "websocket" => &WEBSOCKET_FIELDS,
    "fullUrl" => &FULLURL_FIELDS,
    "MedicinalProductIngredient" => &MEDICINALPRODUCTINGREDIENT_FIELDS,
    "Bundle" => &BUNDLE_FIELDS,
    "NutritionOrder" => &NUTRITIONORDER_FIELDS,
    "observation-bodyweight" => &OBSERVATION_BODYWEIGHT_FIELDS,
    "rdf-type" => &RDF_TYPE_FIELDS,
    "TEL-address" => &TEL_ADDRESS_FIELDS,
    "observation-vitalspanel" => &OBSERVATION_VITALSPANEL_FIELDS,
    "Money" => &MONEY_FIELDS,
    "precision" => &PRECISION_FIELDS,
    "RequestGroup" => &REQUESTGROUP_FIELDS,
    "bodyPosition" => &BODYPOSITION_FIELDS,
    "Flag" => &FLAG_FIELDS,
    "SubstancePolymer" => &SUBSTANCEPOLYMER_FIELDS,
    "EHRS FM Record Lifecycle Event - Audit Event" => &EHRS_FM_RECORD_LIFECYCLE_EVENT___AUDIT_EVENT_FIELDS,
    "usage" => &USAGE_FIELDS,
    "regex" => &REGEX_FIELDS,
    "MessageHeader" => &MESSAGEHEADER_FIELDS,
    "birthTime" => &BIRTHTIME_FIELDS,
    "bidirectional" => &BIDIRECTIONAL_FIELDS,
    "occurredFollowing" => &OCCURREDFOLLOWING_FIELDS,
    "processingTime" => &PROCESSINGTIME_FIELDS,
    "MedicinalProductInteraction" => &MEDICINALPRODUCTINTERACTION_FIELDS,
    "uncertainty" => &UNCERTAINTY_FIELDS,
    "NotificationEndpoint" => &NOTIFICATIONENDPOINT_FIELDS,
    "systemUserType" => &SYSTEMUSERTYPE_FIELDS,
    "ADXP-additionalLocator" => &ADXP_ADDITIONALLOCATOR_FIELDS,
    "partner-name" => &PARTNER_NAME_FIELDS,
    "GuidanceResponse" => &GUIDANCERESPONSE_FIELDS,
    "assembly-order" => &ASSEMBLY_ORDER_FIELDS,
    "Variant" => &VARIANT_FIELDS,
    "SubstanceNucleicAcid" => &SUBSTANCENUCLEICACID_FIELDS,
    "ADXP-houseNumberNumeric" => &ADXP_HOUSENUMBERNUMERIC_FIELDS,
    "isDryWeight" => &ISDRYWEIGHT_FIELDS,
    "initiatingLocation" => &INITIATINGLOCATION_FIELDS,
    "Expression" => &EXPRESSION_FIELDS,
    "observation-bmi" => &OBSERVATION_BMI_FIELDS,
    "sourceReference" => &SOURCEREFERENCE_FIELDS,
    "directedBy" => &DIRECTEDBY_FIELDS,
    "collectionPriority" => &COLLECTIONPRIORITY_FIELDS,
    "RiskAssessment" => &RISKASSESSMENT_FIELDS,
    "unsignedInt" => &UNSIGNEDINT_FIELDS,
    "CDS Hooks RequestGroup" => &CDS_HOOKS_REQUESTGROUP_FIELDS,
    "statusReason" => &STATUSREASON_FIELDS,
    "eventHistory" => &EVENTHISTORY_FIELDS,
    "AD-use" => &AD_USE_FIELDS,
    "VerificationResult" => &VERIFICATIONRESULT_FIELDS,
    "implantStatus" => &IMPLANTSTATUS_FIELDS,
    "observation-oxygensat" => &OBSERVATION_OXYGENSAT_FIELDS,
    "observation-bodyheight" => &OBSERVATION_BODYHEIGHT_FIELDS,
    "ADXP-streetNameType" => &ADXP_STREETNAMETYPE_FIELDS,
    "inheritedExtensibleValueSet" => &INHERITEDEXTENSIBLEVALUESET_FIELDS,
    "Shareable Measure" => &SHAREABLE_MEASURE_FIELDS,
    "PlanDefinition" => &PLANDEFINITION_FIELDS,
    "reference" => &REFERENCE_FIELDS,
    "usageMode" => &USAGEMODE_FIELDS,
    "ParticipantObjectContainsStudy" => &PARTICIPANTOBJECTCONTAINSSTUDY_FIELDS,
    "Extension" => &EXTENSION_FIELDS,
    "Evidence Synthesis Profile" => &EVIDENCE_SYNTHESIS_PROFILE_FIELDS,
    "translatable" => &TRANSLATABLE_FIELDS,
    "importance" => &IMPORTANCE_FIELDS,
    "CopyNumberEvent" => &COPYNUMBEREVENT_FIELDS,
    "Annotation" => &ANNOTATION_FIELDS,
    "label" => &LABEL_FIELDS,
    "ADXP-unitID" => &ADXP_UNITID_FIELDS,
    "entryFormat" => &ENTRYFORMAT_FIELDS,
    "Dosage" => &DOSAGE_FIELDS,
    "MedicinalProductAuthorization" => &MEDICINALPRODUCTAUTHORIZATION_FIELDS,
    "exposureDescription" => &EXPOSUREDESCRIPTION_FIELDS,
    "supportLink" => &SUPPORTLINK_FIELDS,
    "relativeDateTime" => &RELATIVEDATETIME_FIELDS,
    "sibling" => &SIBLING_FIELDS,
    "Timezone Offset" => &TIMEZONE_OFFSET_FIELDS,
    "permitted-value-valueset" => &PERMITTED_VALUE_VALUESET_FIELDS,
    "author" => &AUTHOR_FIELDS,
    "CoverageEligibilityRequest" => &COVERAGEELIGIBILITYREQUEST_FIELDS,
    "focusCode" => &FOCUSCODE_FIELDS,
    "CDS Hooks Service PlanDefinition" => &CDS_HOOKS_SERVICE_PLANDEFINITION_FIELDS,
    "MessageDefinition" => &MESSAGEDEFINITION_FIELDS,
    "uuid" => &UUID_FIELDS,
    "SampledData" => &SAMPLEDDATA_FIELDS,
    "SubstanceSourceMaterial" => &SUBSTANCESOURCEMATERIAL_FIELDS,
    "codegen-super" => &CODEGEN_SUPER_FIELDS,
    "unitValueSet" => &UNITVALUESET_FIELDS,
    "xhtml" => &XHTML_FIELDS,
    "expectation" => &EXPECTATION_FIELDS,
    "Element" => &ELEMENT_FIELDS,
    "causedBy" => &CAUSEDBY_FIELDS,
    "Account" => &ACCOUNT_FIELDS,
    "expansionSource" => &EXPANSIONSOURCE_FIELDS,
    "CodeSystem" => &CODESYSTEM_FIELDS,
    "ADXP-deliveryInstallationQualifier" => &ADXP_DELIVERYINSTALLATIONQUALIFIER_FIELDS,
    "Analysis" => &ANALYSIS_FIELDS,
    "CDS Hooks GuidanceResponse" => &CDS_HOOKS_GUIDANCERESPONSE_FIELDS,
    "SimpleQuantity" => &SIMPLEQUANTITY_FIELDS,
    "parameterSource" => &PARAMETERSOURCE_FIELDS,
    "EvidenceVariable" => &EVIDENCEVARIABLE_FIELDS,
    "location" => &LOCATION_FIELDS,
    "Narrative Link" => &NARRATIVE_LINK_FIELDS,
    "DataElement constraint on ElementDefinition data type" => &DATAELEMENT_CONSTRAINT_ON_ELEMENTDEFINITION_DATA_TYPE_FIELDS,
    "ResearchElementDefinition" => &RESEARCHELEMENTDEFINITION_FIELDS,
    "library" => &LIBRARY_FIELDS,
    "choiceOrientation" => &CHOICEORIENTATION_FIELDS,
    "Condition" => &CONDITION_FIELDS,
    "steward" => &STEWARD_FIELDS,
    "hierarchy" => &HIERARCHY_FIELDS,
    "researchStudy" => &RESEARCHSTUDY_FIELDS,
    "PaymentReconciliation" => &PAYMENTRECONCILIATION_FIELDS,
    "method" => &METHOD_FIELDS,
    "extends" => &EXTENDS_FIELDS,
    "history" => &HISTORY_FIELDS,
    "insurance" => &INSURANCE_FIELDS,
    "relatedArtifact" => &RELATEDARTIFACT_FIELDS,
    "observation-resprate" => &OBSERVATION_RESPRATE_FIELDS,
    "maxValue" => &MAXVALUE_FIELDS,
    "relationship" => &RELATIONSHIP_FIELDS,
    "hidden" => &HIDDEN_FIELDS,
    "Age" => &AGE_FIELDS,
    "Invoice" => &INVOICE_FIELDS,
    "expand-group" => &EXPAND_GROUP_FIELDS,
    "observation-bp" => &OBSERVATION_BP_FIELDS,
    "fhir-type" => &FHIR_TYPE_FIELDS,
    "toocostly" => &TOOCOSTLY_FIELDS,
    "PQ-translation" => &PQ_TRANSLATION_FIELDS,
    "timeOffset" => &TIMEOFFSET_FIELDS,
    "ChargeItem" => &CHARGEITEM_FIELDS,
    "Rendered Value" => &RENDERED_VALUE_FIELDS,
    "Linkage" => &LINKAGE_FIELDS,
    "candidateList" => &CANDIDATELIST_FIELDS,
    "observation-vitalsigns" => &OBSERVATION_VITALSIGNS_FIELDS,
    "List" => &LIST_FIELDS,
    "SubstanceProtein" => &SUBSTANCEPROTEIN_FIELDS,
    "signature" => &SIGNATURE_FIELDS,
    "DeviceRequest" => &DEVICEREQUEST_FIELDS,
    "relevantHistory" => &RELEVANTHISTORY_FIELDS,
    "DeviceUseStatement" => &DEVICEUSESTATEMENT_FIELDS,
    "id" => &ID_FIELDS,
    "boundary-geojson" => &BOUNDARY_GEOJSON_FIELDS,
    "security-category" => &SECURITY_CATEGORY_FIELDS,
    "MedicationStatement" => &MEDICATIONSTATEMENT_FIELDS,
    "BodyStructure" => &BODYSTRUCTURE_FIELDS,
    "uncertaintyType" => &UNCERTAINTYTYPE_FIELDS,
    "ClinicalImpression" => &CLINICALIMPRESSION_FIELDS,
    "Count" => &COUNT_FIELDS,
    "MarketingStatus" => &MARKETINGSTATUS_FIELDS,
    "maxOccurs" => &MAXOCCURS_FIELDS,
    "ADXP-deliveryInstallationArea" => &ADXP_DELIVERYINSTALLATIONAREA_FIELDS,
    "citizenship" => &CITIZENSHIP_FIELDS,
    "Goal" => &GOAL_FIELDS,
    "oauth-uris" => &OAUTH_URIS_FIELDS,
    "Observation" => &OBSERVATION_FIELDS,
    "Allele" => &ALLELE_FIELDS,
    "Questionnaire" => &QUESTIONNAIRE_FIELDS,
    "Shareable PlanDefinition" => &SHAREABLE_PLANDEFINITION_FIELDS,
    "caseSensitive" => &CASESENSITIVE_FIELDS,
    "bestpractice" => &BESTPRACTICE_FIELDS,
    "location-distance" => &LOCATION_DISTANCE_FIELDS,
    "RelatedArtifact" => &RELATEDARTIFACT_FIELDS,
    "MetadataResource" => &METADATARESOURCE_FIELDS,
    "Ratio" => &RATIO_FIELDS,
    "explicit-type-name" => &EXPLICIT_TYPE_NAME_FIELDS,
    "References" => &REFERENCES_FIELDS,
    "Evidence" => &EVIDENCE_FIELDS,
    "Event" => &EVENT_FIELDS,
    "boolean" => &BOOLEAN_FIELDS,
    "preferred" => &PREFERRED_FIELDS,
    "displayCategory" => &DISPLAYCATEGORY_FIELDS,
    "Media" => &MEDIA_FIELDS,
    "itemControl" => &ITEMCONTROL_FIELDS,
    "Human Language" => &HUMAN_LANGUAGE_FIELDS,
    "Signature" => &SIGNATURE_FIELDS,
    "detail" => &DETAIL_FIELDS,
    "supported-system" => &SUPPORTED_SYSTEM_FIELDS,
    "Schedule" => &SCHEDULE_FIELDS,
    "Contract" => &CONTRACT_FIELDS,
    "EHRS FM Record Lifecycle Event - Provenance" => &EHRS_FM_RECORD_LIFECYCLE_EVENT___PROVENANCE_FIELDS,
    "Translation" => &TRANSLATION_FIELDS,
    "keyWord" => &KEYWORD_FIELDS,
    "conceptOrder" => &CONCEPTORDER_FIELDS,
    "sequelTo" => &SEQUELTO_FIELDS,
    "sliderStepValue" => &SLIDERSTEPVALUE_FIELDS,
    "reasonCode" => &REASONCODE_FIELDS,
    "Design Note" => &DESIGN_NOTE_FIELDS,
    "Ordinal Value" => &ORDINAL_VALUE_FIELDS,
    "approachBodyStructure" => &APPROACHBODYSTRUCTURE_FIELDS,
    "partOf" => &PARTOF_FIELDS,
    "Person" => &PERSON_FIELDS,
    "ObservationDefinition" => &OBSERVATIONDEFINITION_FIELDS,
    "ValueSet" => &VALUESET_FIELDS,
    "associatedEncounter" => &ASSOCIATEDENCOUNTER_FIELDS,
    "decimal" => &DECIMAL_FIELDS,
    "ADXP-streetAddressLine" => &ADXP_STREETADDRESSLINE_FIELDS,
    "Gene" => &GENE_FIELDS,
    "supportingInfo" => &SUPPORTINGINFO_FIELDS,
    "equivalence" => &EQUIVALENCE_FIELDS,
    "EN-representation" => &EN_REPRESENTATION_FIELDS,
    "summary" => &SUMMARY_FIELDS,
    "Definition" => &DEFINITION_FIELDS,
    "lastReviewDate" => &LASTREVIEWDATE_FIELDS,
    "Reference" => &REFERENCE_FIELDS,
    "PractitionerRole" => &PRACTITIONERROLE_FIELDS,
    "selector" => &SELECTOR_FIELDS,
    "Narrative" => &NARRATIVE_FIELDS,
    "proficiency" => &PROFICIENCY_FIELDS,
    "progressStatus" => &PROGRESSSTATUS_FIELDS,
    "animal" => &ANIMAL_FIELDS,
    "Ancestry" => &ANCESTRY_FIELDS,
    "ADXP-streetName" => &ADXP_STREETNAME_FIELDS,
    "exposureDate" => &EXPOSUREDATE_FIELDS,
    "exact" => &EXACT_FIELDS,
    "authority" => &AUTHORITY_FIELDS,
    "strengthOfRecommendation" => &STRENGTHOFRECOMMENDATION_FIELDS,
    "template-status" => &TEMPLATE_STATUS_FIELDS,
    "Timing" => &TIMING_FIELDS,
    "DocumentManifest" => &DOCUMENTMANIFEST_FIELDS,
    "MedicinalProductUndesirableEffect" => &MEDICINALPRODUCTUNDESIRABLEEFFECT_FIELDS,
    "Period" => &PERIOD_FIELDS,
    "citation" => &CITATION_FIELDS,
    "gatewayDevice" => &GATEWAYDEVICE_FIELDS,
    "ADXP-deliveryMode" => &ADXP_DELIVERYMODE_FIELDS,
    "encounterType" => &ENCOUNTERTYPE_FIELDS,
    "Location" => &LOCATION_FIELDS,
    "string" => &STRING_FIELDS,
    "AminoAcidChange" => &AMINOACIDCHANGE_FIELDS,
    "ADXP-direction" => &ADXP_DIRECTION_FIELDS,
    "CareTeam" => &CARETEAM_FIELDS,
    "Shareable ValueSet" => &SHAREABLE_VALUESET_FIELDS,
    "approvalDate" => &APPROVALDATE_FIELDS,
    "Specimen" => &SPECIMEN_FIELDS,
    "secondaryFinding" => &SECONDARYFINDING_FIELDS,
    "AllergyIntolerance" => &ALLERGYINTOLERANCE_FIELDS,
    "effectivePeriod" => &EFFECTIVEPERIOD_FIELDS,
    "mothersMaidenName" => &MOTHERSMAIDENNAME_FIELDS,
    "unit" => &UNIT_FIELDS,
    "test" => &TEST_FIELDS,
    "initiatingOrganization" => &INITIATINGORGANIZATION_FIELDS,
    "ResearchStudy" => &RESEARCHSTUDY_FIELDS,
    "nationality" => &NATIONALITY_FIELDS,
    "markdown" => &MARKDOWN_FIELDS,
    "minLength" => &MINLENGTH_FIELDS,
    "Subscription" => &SUBSCRIPTION_FIELDS,
    "Range" => &RANGE_FIELDS,
    "SupplyRequest" => &SUPPLYREQUEST_FIELDS,
    "Instance" => &INSTANCE_FIELDS,
    "ResearchDefinition" => &RESEARCHDEFINITION_FIELDS,
    "Provenance Relevant History" => &PROVENANCE_RELEVANT_HISTORY_FIELDS,
    "ImagingStudy" => &IMAGINGSTUDY_FIELDS,
    "Shareable Library" => &SHAREABLE_LIBRARY_FIELDS,
    "systemUserLanguage" => &SYSTEMUSERLANGUAGE_FIELDS,
    "system" => &SYSTEM_FIELDS,
    "DataRequirement" => &DATAREQUIREMENT_FIELDS,
    "area" => &AREA_FIELDS,
    "ancestor" => &ANCESTOR_FIELDS,
    "Request" => &REQUEST_FIELDS,
    "systemName" => &SYSTEMNAME_FIELDS,
    "ServiceRequest-Genetics" => &SERVICEREQUEST_GENETICS_FIELDS,
    "Identifier" => &IDENTIFIER_FIELDS,
    "Encrypted" => &ENCRYPTED_FIELDS,
    "DomainResource" => &DOMAINRESOURCE_FIELDS,
    "ImmunizationEvaluation" => &IMMUNIZATIONEVALUATION_FIELDS,
    "measureInfo" => &MEASUREINFO_FIELDS,
    "detectedIssue" => &DETECTEDISSUE_FIELDS,
    "fmm-no-warnings" => &FMM_NO_WARNINGS_FIELDS,
    "Device" => &DEVICE_FIELDS,
    "SpecimenDefinition" => &SPECIMENDEFINITION_FIELDS,
    "ADXP-deliveryModeIdentifier" => &ADXP_DELIVERYMODEIDENTIFIER_FIELDS,
    "objectClassProperty" => &OBJECTCLASSPROPERTY_FIELDS,
    "receivingPerson" => &RECEIVINGPERSON_FIELDS,
    "Coding" => &CODING_FIELDS,
    "Variable" => &VARIABLE_FIELDS,
    "TestScript" => &TESTSCRIPT_FIELDS,
    "systemRef" => &SYSTEMREF_FIELDS,
    "substanceExposureRisk" => &SUBSTANCEEXPOSURERISK_FIELDS,
    "SearchParameter" => &SEARCHPARAMETER_FIELDS,
    "risk" => &RISK_FIELDS,
    "alternate" => &ALTERNATE_FIELDS,
    "BackboneElement" => &BACKBONEELEMENT_FIELDS,
    "period" => &PERIOD_FIELDS,
    "adaptiveFeedingDevice" => &ADAPTIVEFEEDINGDEVICE_FIELDS,
    "MedicinalProduct" => &MEDICINALPRODUCT_FIELDS,
    "CompartmentDefinition" => &COMPARTMENTDEFINITION_FIELDS,
    "ExplanationOfBenefit" => &EXPLANATIONOFBENEFIT_FIELDS,
    "reason" => &REASON_FIELDS,
    "Attachment" => &ATTACHMENT_FIELDS,
    "Witness" => &WITNESS_FIELDS,
    "replaces" => &REPLACES_FIELDS,
    "EpisodeOfCare" => &EPISODEOFCARE_FIELDS,
    "summaryOf" => &SUMMARYOF_FIELDS,
    "questionnaireRequest" => &QUESTIONNAIREREQUEST_FIELDS,
    "MedicationDispense" => &MEDICATIONDISPENSE_FIELDS,
    "dueTo" => &DUETO_FIELDS,
    "Claim" => &CLAIM_FIELDS,
    "changeBase" => &CHANGEBASE_FIELDS,
    "observation-bodytemp" => &OBSERVATION_BODYTEMP_FIELDS,
    "observation-heartrate" => &OBSERVATION_HEARTRATE_FIELDS,
    "Example Lipid Profile" => &EXAMPLE_LIPID_PROFILE_FIELDS,
    "AuditEvent" => &AUDITEVENT_FIELDS,
    "assertedDate" => &ASSERTEDDATE_FIELDS,
    "SOPClass" => &SOPCLASS_FIELDS,
    "StructureDefinition" => &STRUCTUREDEFINITION_FIELDS,
    "glstring" => &GLSTRING_FIELDS,
    "namespace" => &NAMESPACE_FIELDS,
    "positiveInt" => &POSITIVEINT_FIELDS,
    "Geolocation" => &GEOLOCATION_FIELDS,
    "ADXP-deliveryAddressLine" => &ADXP_DELIVERYADDRESSLINE_FIELDS,
    "locationPerformed" => &LOCATIONPERFORMED_FIELDS,
    "MolecularSequence" => &MOLECULARSEQUENCE_FIELDS,
    "ServiceRequest" => &SERVICEREQUEST_FIELDS,
    "MedicationRequest" => &MEDICATIONREQUEST_FIELDS,
    "Endpoint" => &ENDPOINT_FIELDS,
    "own-name" => &OWN_NAME_FIELDS,
    "Encounter" => &ENCOUNTER_FIELDS,
    "cadavericDonor" => &CADAVERICDONOR_FIELDS,
    "instantiatesCanonical" => &INSTANTIATESCANONICAL_FIELDS,
    "ChargeItemDefinition" => &CHARGEITEMDEFINITION_FIELDS,
    "PICO Element Profile" => &PICO_ELEMENT_PROFILE_FIELDS,
    "ADXP-houseNumber" => &ADXP_HOUSENUMBER_FIELDS,
    "sequenceNumber" => &SEQUENCENUMBER_FIELDS,
    "special-status" => &SPECIAL_STATUS_FIELDS,
    "OperationDefinition" => &OPERATIONDEFINITION_FIELDS,
    "ruledOut" => &RULEDOUT_FIELDS,
    "normative-version" => &NORMATIVE_VERSION_FIELDS,
    "supplement" => &SUPPLEMENT_FIELDS,
};

/// Get field information for a specific field in a type
pub fn get_field_info(type_name: &str, field_name: &str) -> Option<&'static FieldInfo> {
    FHIR_TYPE_REGISTRY
        .get(type_name)
        .and_then(|fields| fields.get(field_name))
}

/// Resolve a nested path like "Patient.name.given" to its field type
pub fn resolve_path(path: &str) -> Option<&'static FhirFieldType> {
    let parts: Vec<&str> = path.split('.').collect();
    if parts.is_empty() {
        return None;
    }

    let mut current_type_name = parts[0];

    for (idx, &field_name) in parts[1..].iter().enumerate() {
        let field_info = get_field_info(current_type_name, field_name)?;

        // If this is the last field, return its type
        if idx == parts.len() - 2 {
            return Some(&field_info.field_type);
        }

        // Otherwise, navigate to the next type
        match &field_info.field_type {
            FhirFieldType::Complex(type_name) | FhirFieldType::BackboneElement(type_name) => {
                current_type_name = type_name;
            }
            _ => return None, // Can't navigate further
        }
    }

    None
}
