library GoldenBooleanLogic version '1.0.0'

define TrueAndTrue: true and true
define TrueAndFalse: true and false
define FalseAndFalse: false and false
define TrueOrFalse: true or false
define FalseOrFalse: false or false
define NotTrue: not true
define NotFalse: not false
define NullAndTrue: null and true
define NullAndFalse: null and false
define TrueOrNull: true or null
define FalseOrNull: false or null
